FROM rust:latest AS builder
WORKDIR /app
COPY . .
RUN cargo build --release
FROM debian:trixie-slim
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/irrigation-advisor-backend .
EXPOSE 3000
CMD ["./irrigation-advisor-backend"]